### ISSUE TITLE
All forms are currently sent with the "multipart/form-data" header. Although there is no <input type ="file"> in the form.

### ISSUE THREAD

**Issue by viasors** [twinstone/tdi#34]
**Environment**
- jQuery 2.1.4
- TDI 1.9.1

**Steps to reproduce**
Submit a form with text inputs only (TDI class included ;)).

**Observed behaviour**
The POST is sent with "multipart/form-data" header. Although it should contain a "application/x-www-form-urlencoded" header.

Related to the #11 probably..

**Comment by centi** [comment]
I used FormData for all forms with POST method, which is wrong. When using FormData interface, the data are always sent as multipart, see: https://developer.mozilla.org/en/docs/Web/API/FormData

Now only the forms with file uploads use FormData.

**Comment by msevcenko** [comment]
This change broke my app.

What about the situation when the form is explicitly marked as `enctype="multipart/form-data"`? Should't it honor this requirement and submit as multipart?

The form has enctype="multipart/form-data", because it submits large data, which wouldn't fit into servers limit of url-encoded data.

EDIT: in fact, isn't the enctype="multipart/form-data" the decisive information whether to send as multipart, not the presence or absence of file data? IMO if you want to submit file data, you SHOULD mark the form as enctype="multipart/form-data", it won't get multipart just because form contains file data.

EDIT: submitted as new bug https://github.com/twinstone/tdi/issues/54
